/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

/**
 *
 * @author WC
 */
public class comprarIngresso extends javax.swing.JFrame {

    /**
     * Creates new form comprarIngresso
     */
    public comprarIngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPainel = new javax.swing.JLabel();
        imagemEspetaculo1 = new javax.swing.JLabel();
        imagemEspetaculo2 = new javax.swing.JLabel();
        imagemEspetaculo3 = new javax.swing.JLabel();
        botaoEspetaculo1 = new javax.swing.JButton();
        botaoEspetaculo2 = new javax.swing.JButton();
        botaoEspetaculo3 = new javax.swing.JButton();
        tituloSessao = new javax.swing.JLabel();
        tituloArea = new javax.swing.JLabel();
        botaoSessaoManha = new javax.swing.JButton();
        botaoSessaoTarde = new javax.swing.JButton();
        botaoSessaoNoite = new javax.swing.JButton();
        botaoAreaPlateiaA = new javax.swing.JButton();
        botaoAreaPlateiaA1 = new javax.swing.JButton();
        botaoAreaPlateiaA2 = new javax.swing.JButton();
        botaoAreaPlateiaA3 = new javax.swing.JButton();
        botaoAreaPlateiaA4 = new javax.swing.JButton();
        botaoAreaPlateiaA5 = new javax.swing.JButton();
        botaoAreaPlateiaA6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tituloPainel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloPainel.setForeground(new java.awt.Color(21, 63, 69));
        tituloPainel.setText("Obras em Cartaz ");

        imagemEspetaculo1.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\iloveimg-resized\\filme1PI.jpg")); // NOI18N

        imagemEspetaculo2.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\iloveimg-resized\\filme2PIsemfundo.png")); // NOI18N
        imagemEspetaculo2.setText("jLabel4");

        imagemEspetaculo3.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\iloveimg-resized\\filme3PI.jpg")); // NOI18N

        botaoEspetaculo1.setBackground(new java.awt.Color(217, 217, 217));
        botaoEspetaculo1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo1.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo1.setText("The Batman");
        botaoEspetaculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEspetaculo1ActionPerformed(evt);
            }
        });

        botaoEspetaculo2.setBackground(new java.awt.Color(217, 217, 217));
        botaoEspetaculo2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo2.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo2.setText("Kill Bill: Volume 1");
        botaoEspetaculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEspetaculo2ActionPerformed(evt);
            }
        });

        botaoEspetaculo3.setBackground(new java.awt.Color(217, 217, 217));
        botaoEspetaculo3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo3.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo3.setText("Django Livre");
        botaoEspetaculo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEspetaculo3ActionPerformed(evt);
            }
        });

        tituloSessao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloSessao.setForeground(new java.awt.Color(21, 63, 69));
        tituloSessao.setText("Sessão");

        tituloArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloArea.setText("Área");

        botaoSessaoManha.setBackground(new java.awt.Color(217, 217, 217));
        botaoSessaoManha.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoSessaoManha.setForeground(new java.awt.Color(21, 63, 69));
        botaoSessaoManha.setText("Manhã");
        botaoSessaoManha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSessaoManhaActionPerformed(evt);
            }
        });

        botaoSessaoTarde.setBackground(new java.awt.Color(217, 217, 217));
        botaoSessaoTarde.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoSessaoTarde.setForeground(new java.awt.Color(21, 63, 69));
        botaoSessaoTarde.setText("Tarde");
        botaoSessaoTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSessaoTardeActionPerformed(evt);
            }
        });

        botaoSessaoNoite.setBackground(new java.awt.Color(217, 217, 217));
        botaoSessaoNoite.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoSessaoNoite.setForeground(new java.awt.Color(21, 63, 69));
        botaoSessaoNoite.setText("Noite");
        botaoSessaoNoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSessaoNoiteActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA.setText("Plateia A - R$40");
        botaoAreaPlateiaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaAActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA1.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA1.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA1.setText("Plateia B - R$60");
        botaoAreaPlateiaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA1ActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA2.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA2.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA2.setText("Camarote 1-3 R$80");
        botaoAreaPlateiaA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA2ActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA3.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA3.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA3.setText("Camarote 4-5 R$80");
        botaoAreaPlateiaA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA3ActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA4.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA4.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA4.setText("Frisa 1-3 R$120");
        botaoAreaPlateiaA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA4ActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA5.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA5.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA5.setText("Frisa 4-6 R$120");
        botaoAreaPlateiaA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA5ActionPerformed(evt);
            }
        });

        botaoAreaPlateiaA6.setBackground(new java.awt.Color(217, 217, 217));
        botaoAreaPlateiaA6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoAreaPlateiaA6.setForeground(new java.awt.Color(21, 63, 69));
        botaoAreaPlateiaA6.setText("Balcão Nobre R$250");
        botaoAreaPlateiaA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAreaPlateiaA6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(21, 63, 69));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");

        jButton2.setBackground(new java.awt.Color(39, 141, 98));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Escolher Poltrona");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(tituloPainel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(tituloSessao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(tituloArea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botaoEspetaculo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(imagemEspetaculo1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(botaoAreaPlateiaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoSessaoManha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(botaoSessaoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(botaoAreaPlateiaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(imagemEspetaculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(botaoEspetaculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(botaoEspetaculo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(imagemEspetaculo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoSessaoNoite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoAreaPlateiaA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(botaoAreaPlateiaA4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoAreaPlateiaA5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(botaoAreaPlateiaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoAreaPlateiaA6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloPainel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagemEspetaculo1)
                    .addComponent(imagemEspetaculo2)
                    .addComponent(imagemEspetaculo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEspetaculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEspetaculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEspetaculo3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(tituloSessao)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSessaoManha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSessaoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSessaoNoite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(tituloArea)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAreaPlateiaA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAreaPlateiaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAreaPlateiaA2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAreaPlateiaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAreaPlateiaA4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAreaPlateiaA5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoAreaPlateiaA6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSessaoNoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSessaoNoiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSessaoNoiteActionPerformed

    private void botaoSessaoTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSessaoTardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSessaoTardeActionPerformed

    private void botaoSessaoManhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSessaoManhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSessaoManhaActionPerformed

    private void botaoEspetaculo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEspetaculo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEspetaculo3ActionPerformed

    private void botaoEspetaculo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEspetaculo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEspetaculo2ActionPerformed

    private void botaoEspetaculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEspetaculo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEspetaculo1ActionPerformed

    private void botaoAreaPlateiaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaAActionPerformed

    private void botaoAreaPlateiaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA1ActionPerformed

    private void botaoAreaPlateiaA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA2ActionPerformed

    private void botaoAreaPlateiaA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA3ActionPerformed

    private void botaoAreaPlateiaA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA4ActionPerformed

    private void botaoAreaPlateiaA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA5ActionPerformed

    private void botaoAreaPlateiaA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAreaPlateiaA6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAreaPlateiaA6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comprarIngresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAreaPlateiaA;
    private javax.swing.JButton botaoAreaPlateiaA1;
    private javax.swing.JButton botaoAreaPlateiaA2;
    private javax.swing.JButton botaoAreaPlateiaA3;
    private javax.swing.JButton botaoAreaPlateiaA4;
    private javax.swing.JButton botaoAreaPlateiaA5;
    private javax.swing.JButton botaoAreaPlateiaA6;
    private javax.swing.JButton botaoEspetaculo1;
    private javax.swing.JButton botaoEspetaculo2;
    private javax.swing.JButton botaoEspetaculo3;
    private javax.swing.JButton botaoSessaoManha;
    private javax.swing.JButton botaoSessaoNoite;
    private javax.swing.JButton botaoSessaoTarde;
    private javax.swing.JLabel imagemEspetaculo1;
    private javax.swing.JLabel imagemEspetaculo2;
    private javax.swing.JLabel imagemEspetaculo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloArea;
    private javax.swing.JLabel tituloPainel;
    private javax.swing.JLabel tituloSessao;
    // End of variables declaration//GEN-END:variables
}
