/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author WC
 */
public class JanelaPrincipal2 extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private JPanel painelPrincipal;


    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal2() {
        initComponents();
        initComponentsExtra();
    }

        private void initComponentsExtra() {
        // Configuração do layout de painéis
        cardLayout = new CardLayout();
        painelPrincipal = new JPanel(cardLayout);

        // Criação dos painéis (cada um representando uma tela)
        PainelComprarIngresso painelComprar = new PainelComprarIngresso(); // Adapte o construtor conforme necessário
        PainelMeusIngressos painelMeusIngressos = new PainelMeusIngressos(); // Adapte o construtor conforme necessário
        PainelEstatisticasDeVendas painelEstatisticas = new PainelEstatisticasDeVendas(); // Adapte o construtor conforme necessário

        // Painel de login ou outro painel inicial
        PainelLogin painelLogin = new PainelLogin(); // Ajuste conforme necessário

        // Adicionando painéis ao painel principal com CardLayout
        painelPrincipal.add(painelLogin, "Login");
        painelPrincipal.add(painelComprar, "Comprar");
        painelPrincipal.add(painelMeusIngressos, "Meus Ingressos");
        painelPrincipal.add(painelEstatisticas, "Estatísticas");

        cardLayout.show(painelPrincipal, "Login");
        setContentPane(painelPrincipal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        botaoComprarIngresso = new javax.swing.JButton();
        botaoMeusIngressos = new javax.swing.JButton();
        botaoEstatisticasVendas = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        botaoComprarIngresso.setBackground(new java.awt.Color(39, 141, 98));
        botaoComprarIngresso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoComprarIngresso.setForeground(new java.awt.Color(255, 255, 255));
        botaoComprarIngresso.setText("Comprar Ingressos");
        botaoComprarIngresso.setPreferredSize(new java.awt.Dimension(500, 32));
        botaoComprarIngresso.addActionListener(evt -> botaoComprarIngressoActionPerformed(evt));

        botaoMeusIngressos.setBackground(new java.awt.Color(39, 141, 98));
        botaoMeusIngressos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoMeusIngressos.setForeground(new java.awt.Color(255, 255, 255));
        botaoMeusIngressos.setText("Meus Ingressos");
        botaoMeusIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMeusIngressosActionPerformed(evt);
            }
        });

        botaoEstatisticasVendas.setBackground(new java.awt.Color(39, 141, 98));
        botaoEstatisticasVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEstatisticasVendas.setForeground(new java.awt.Color(255, 255, 255));
        botaoEstatisticasVendas.setText("Estátisticas de Vendas");
        botaoEstatisticasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstatisticasVendasActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(21, 63, 69));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        // Layout do painel
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoComprarIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEstatisticasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(373, 373, 373))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoComprarIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoEstatisticasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoComprarIngressoActionPerformed(java.awt.event.ActionEvent evt) {
        cardLayout.show(painelPrincipal, "Comprar");
    }

    private void botaoMeusIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMeusIngressosActionPerformed
        // TODO add your handling code here:
        cardLayout.show(painelPrincipal, "Meus Ingressos");
    }//GEN-LAST:event_botaoMeusIngressosActionPerformed

    private void botaoEstatisticasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstatisticasVendasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(painelPrincipal, "Meus Ingressos");
    }//GEN-LAST:event_botaoEstatisticasVendasActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            new JanelaPrincipal2().setVisible(true); // Aqui a janela deve ser visível

        });
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComprarIngresso;
    private javax.swing.JButton botaoEstatisticasVendas;
    private javax.swing.JButton botaoMeusIngressos;
    private javax.swing.JButton botaoSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
