/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author WC
 */
public class PainelComprarIngresso extends javax.swing.JPanel {
    private CardLayout cardLayout;
    private JPanel painelPrincipal;
    /**
     * Creates new form PainelComprarIngresso
     */
    // Variáveis para armazenar as seleções
    private String espetaculoSelecionado = "";
    private String sessaoSelecionada = "";
    private String areaSelecionada = "";
    // Declaração dos ButtonGroups
    private ButtonGroup grupoEspetaculos;
    private ButtonGroup grupoSessoes;
    private ButtonGroup grupoAreas;
    public PainelComprarIngresso(JPanel painelPrincipal) {
        this.painelPrincipal = painelPrincipal;  // Armazene a referência do painel principal
        initComponents(); // Chame apenas uma vez
        // Inicialize os componentes do painel aqui, como o botão "Voltar"
        inicializarButtonGroups(); // Inicialize os grupos de botões

    }
    // Método para inicializar os ButtonGroups
    private void inicializarButtonGroups() {
        // Inicializa os grupos de botões
        grupoEspetaculos = new ButtonGroup();
        grupoSessoes = new ButtonGroup();
        grupoAreas = new ButtonGroup();

        // Adiciona os botões de espetáculo ao grupo
        grupoEspetaculos.add(botaoEspetaculo1);
        grupoEspetaculos.add(botaoEspetaculo2);
        grupoEspetaculos.add(botaoEspetaculo3);

        // Adiciona os botões de sessão ao grupo
        grupoSessoes.add(botaoManha);
        grupoSessoes.add(botaoTarde);
        grupoSessoes.add(botaoNoite);

        // Adiciona os botões de área ao grupo
        grupoAreas.add(botaoPlateiaA);
        grupoAreas.add(botaoPlateiaB);
        grupoAreas.add(botaoCamarote1a3);
        grupoAreas.add(botaoCamarote4e5);
        grupoAreas.add(botaoFrisa1a3);
        grupoAreas.add(botaoFrisa4a6);
        grupoAreas.add(botaoBalcaoNobre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPainel = new javax.swing.JLabel();
        imagemEspetaculo1 = new javax.swing.JLabel();
        imagemEspetaculo2 = new javax.swing.JLabel();
        imagemEspetaculo3 = new javax.swing.JLabel();
        tituloSessao = new javax.swing.JLabel();
        tituloArea = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoEscolherPoltrona = new javax.swing.JButton();
        botaoEspetaculo1 = new javax.swing.JToggleButton();
        botaoEspetaculo2 = new javax.swing.JToggleButton();
        botaoEspetaculo3 = new javax.swing.JToggleButton();
        botaoManha = new javax.swing.JToggleButton();
        botaoTarde = new javax.swing.JToggleButton();
        botaoNoite = new javax.swing.JToggleButton();
        botaoPlateiaA = new javax.swing.JToggleButton();
        botaoPlateiaB = new javax.swing.JToggleButton();
        botaoCamarote4e5 = new javax.swing.JToggleButton();
        botaoCamarote1a3 = new javax.swing.JToggleButton();
        botaoFrisa1a3 = new javax.swing.JToggleButton();
        botaoFrisa4a6 = new javax.swing.JToggleButton();
        botaoBalcaoNobre = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloPainel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloPainel.setForeground(new java.awt.Color(21, 63, 69));
        tituloPainel.setText("Obras em Cartaz ");

        imagemEspetaculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filme1PI.jpg"))); // NOI18N

        imagemEspetaculo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filme2PIsemfundo.png"))); // NOI18N
        imagemEspetaculo2.setText("jLabel4");

        imagemEspetaculo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filme3PI.jpg"))); // NOI18N

        tituloSessao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloSessao.setForeground(new java.awt.Color(21, 63, 69));
        tituloSessao.setText("Sessão");

        tituloArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloArea.setText("Área");

        botaoVoltar.setBackground(new java.awt.Color(21, 63, 69));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });


        botaoEscolherPoltrona.setBackground(new java.awt.Color(39, 141, 98));
        botaoEscolherPoltrona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEscolherPoltrona.setForeground(new java.awt.Color(255, 255, 255));
        botaoEscolherPoltrona.setText("Escolher Poltrona");
        botaoEscolherPoltrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherPoltronaActionPerformed(evt);
            }
        });

        botaoEspetaculo1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo1.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo1.setText("The Batman");
        botaoEspetaculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espetaculoSelecionado = "The Batman";
            }
        });

        botaoEspetaculo2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo2.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo2.setText("Kill Bill: Volume 1");
        botaoEspetaculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espetaculoSelecionado = "Kill Bill: Volume 1";
            }
        });

        botaoEspetaculo3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoEspetaculo3.setForeground(new java.awt.Color(21, 63, 69));
        botaoEspetaculo3.setText("Django Livre");
        botaoEspetaculo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espetaculoSelecionado = "Django Livre";
            }
        });

        botaoManha.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoManha.setForeground(new java.awt.Color(21, 63, 69));
        botaoManha.setText("Manhã");
        botaoManha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessaoSelecionada = "Manhã";
            }
        });

        botaoTarde.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoTarde.setForeground(new java.awt.Color(21, 63, 69));
        botaoTarde.setText("Tarde");
        botaoTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessaoSelecionada = "Tarde";
            }
        });


        botaoNoite.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoNoite.setForeground(new java.awt.Color(21, 63, 69));
        botaoNoite.setText("Noite");
        botaoNoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessaoSelecionada = "Noite";
            }
        });

        botaoPlateiaA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoPlateiaA.setForeground(new java.awt.Color(21, 63, 69));
        botaoPlateiaA.setText("Plateia A - R$40");
        botaoPlateiaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Plateia A - R$40";
            }
        });

        botaoPlateiaB.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoPlateiaB.setForeground(new java.awt.Color(21, 63, 69));
        botaoPlateiaB.setText("Plateia B - R$80");
        botaoPlateiaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Plateia B - R$80";
            }
        });

        botaoCamarote4e5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoCamarote4e5.setForeground(new java.awt.Color(21, 63, 69));
        botaoCamarote4e5.setText("Camarote 4-5 R$80");
        botaoCamarote4e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Camarote 4-5 R$80";
            }
        });

        botaoCamarote1a3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoCamarote1a3.setForeground(new java.awt.Color(21, 63, 69));
        botaoCamarote1a3.setText("Camarote 1-3 R$80");
        botaoCamarote1a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Camarote 1-3 R$80";
            }
        });


        botaoFrisa1a3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoFrisa1a3.setForeground(new java.awt.Color(21, 63, 69));
        botaoFrisa1a3.setText("Frisa 1-3 R$120");
        botaoFrisa1a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Frisa 1-3 R$120";
            }
        });


        botaoFrisa4a6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoFrisa4a6.setForeground(new java.awt.Color(21, 63, 69));
        botaoFrisa4a6.setText("Frisa 4-6 R$120");
        botaoFrisa4a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Frisa 4-6 R$120";
            }
        });

        botaoBalcaoNobre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        botaoBalcaoNobre.setForeground(new java.awt.Color(21, 63, 69));
        botaoBalcaoNobre.setText("Balcão Nobre");
        botaoBalcaoNobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelecionada = "Balcão Nobre R$200";
            }
        });

        // Adiciona o ActionListener para o botão de voltar
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEscolherPoltrona)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(tituloPainel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(tituloSessao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(tituloArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPlateiaA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCamarote4e5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBalcaoNobre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoFrisa1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPlateiaB, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoCamarote1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoFrisa4a6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoManha, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoEspetaculo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagemEspetaculo1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(imagemEspetaculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(botaoEspetaculo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(botaoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoNoite, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botaoEspetaculo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagemEspetaculo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloPainel)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemEspetaculo1)
                    .addComponent(imagemEspetaculo2)
                    .addComponent(imagemEspetaculo3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoEspetaculo1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(botaoEspetaculo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEspetaculo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(tituloSessao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoManha, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(botaoTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoNoite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(tituloArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPlateiaA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPlateiaB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCamarote1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCamarote4e5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFrisa1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFrisa4a6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoBalcaoNobre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(botaoEscolherPoltrona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEscolherPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherPoltronaActionPerformed
        // TODO add your handling code here:
        // Exemplo de ação ao escolher poltrona
        System.out.println("Espetáculo Selecionado: " + espetaculoSelecionado);
        System.out.println("Sessão Selecionada: " + sessaoSelecionada);
        System.out.println("Área Selecionada: " + areaSelecionada);
    }//GEN-LAST:event_botaoEscolherPoltronaActionPerformed

    private void botaoEspetaculo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEspetaculo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEspetaculo3ActionPerformed
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        navigateToPanel("Menu");  // Nome correto do painel para retornar
    }
    private void navigateToPanel(String panelName) {
        CardLayout layout = (CardLayout) painelPrincipal.getLayout(); // Certifique-se de que o painel principal use CardLayout
        layout.show(painelPrincipal, panelName); // Navega para o painel especificado
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoBalcaoNobre;
    private javax.swing.JToggleButton botaoCamarote1a3;
    private javax.swing.JToggleButton botaoCamarote4e5;
    private javax.swing.JButton botaoEscolherPoltrona;
    private javax.swing.JToggleButton botaoEspetaculo1;
    private javax.swing.JToggleButton botaoEspetaculo2;
    private javax.swing.JToggleButton botaoEspetaculo3;
    private javax.swing.JToggleButton botaoFrisa1a3;
    private javax.swing.JToggleButton botaoFrisa4a6;
    private javax.swing.JToggleButton botaoManha;
    private javax.swing.JToggleButton botaoNoite;
    private javax.swing.JToggleButton botaoPlateiaA;
    private javax.swing.JToggleButton botaoPlateiaB;
    private javax.swing.JToggleButton botaoTarde;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel imagemEspetaculo1;
    private javax.swing.JLabel imagemEspetaculo2;
    private javax.swing.JLabel imagemEspetaculo3;
    private javax.swing.JLabel tituloArea;
    private javax.swing.JLabel tituloPainel;
    private javax.swing.JLabel tituloSessao;
    // End of variables declaration//GEN-END:variables
}
