/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

/**
 *
 * @author WC
 */
public class PainelFrisa1to3 extends javax.swing.JPanel {

    /**
     * Creates new form PainelFrisa1to3
     */
    public PainelFrisa1to3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaFrisa1 = new javax.swing.JLabel();
        painelDisponivel = new javax.swing.JPanel();
        etiquetaDisponivel = new javax.swing.JLabel();
        painelPoltronas = new javax.swing.JPanel();
        poltrona1frisa1 = new javax.swing.JToggleButton();
        poltrona2frisa1 = new javax.swing.JToggleButton();
        poltrona3frisa1 = new javax.swing.JToggleButton();
        poltrona4frisa1 = new javax.swing.JToggleButton();
        poltrona5frisa1 = new javax.swing.JToggleButton();
        poltrona1frisa2 = new javax.swing.JToggleButton();
        poltrona2frisa2 = new javax.swing.JToggleButton();
        poltrona3frisa2 = new javax.swing.JToggleButton();
        poltrona4frisa2 = new javax.swing.JToggleButton();
        poltrona5frisa2 = new javax.swing.JToggleButton();
        polltrona1frisa3 = new javax.swing.JToggleButton();
        poltrona2frisa3 = new javax.swing.JToggleButton();
        poltrona3frisa3 = new javax.swing.JToggleButton();
        poltrona4frisa3 = new javax.swing.JToggleButton();
        poltrona5frisa3 = new javax.swing.JToggleButton();
        etiquetaOcupado = new javax.swing.JLabel();
        painelOcupado = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        botaoConfirmaPoltrona = new javax.swing.JButton();
        etiquetaFrisa2 = new javax.swing.JLabel();
        etiquetaFrisa3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaTitulo.setText("Escolha a Poltrona");

        etiquetaFrisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaFrisa1.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaFrisa1.setText("Frisa 1");

        painelDisponivel.setBackground(new java.awt.Color(39, 141, 98));
        painelDisponivel.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout painelDisponivelLayout = new javax.swing.GroupLayout(painelDisponivel);
        painelDisponivel.setLayout(painelDisponivelLayout);
        painelDisponivelLayout.setHorizontalGroup(
            painelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        painelDisponivelLayout.setVerticalGroup(
            painelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        etiquetaDisponivel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaDisponivel.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaDisponivel.setText("Disponível");

        painelPoltronas.setPreferredSize(new java.awt.Dimension(730, 415));

        poltrona1frisa1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona1frisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona1frisa1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona1frisa1.setText("1");
        poltrona1frisa1.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona1frisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona1frisa1ActionPerformed(evt);
            }
        });

        poltrona2frisa1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona2frisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona2frisa1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona2frisa1.setText("2");
        poltrona2frisa1.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona2frisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona2frisa1ActionPerformed(evt);
            }
        });

        poltrona3frisa1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona3frisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona3frisa1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona3frisa1.setText("3");
        poltrona3frisa1.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona3frisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona3frisa1ActionPerformed(evt);
            }
        });

        poltrona4frisa1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona4frisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona4frisa1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona4frisa1.setText("4");
        poltrona4frisa1.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona4frisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona4frisa1ActionPerformed(evt);
            }
        });

        poltrona5frisa1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona5frisa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona5frisa1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona5frisa1.setText("5");
        poltrona5frisa1.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona5frisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona5frisa1ActionPerformed(evt);
            }
        });

        poltrona1frisa2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona1frisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona1frisa2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona1frisa2.setText("1");
        poltrona1frisa2.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona1frisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona1frisa2ActionPerformed(evt);
            }
        });

        poltrona2frisa2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona2frisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona2frisa2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona2frisa2.setText("2");
        poltrona2frisa2.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona2frisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona2frisa2ActionPerformed(evt);
            }
        });

        poltrona3frisa2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona3frisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona3frisa2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona3frisa2.setText("3");
        poltrona3frisa2.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona3frisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona3frisa2ActionPerformed(evt);
            }
        });

        poltrona4frisa2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona4frisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona4frisa2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona4frisa2.setText("4");
        poltrona4frisa2.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona4frisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona4frisa2ActionPerformed(evt);
            }
        });

        poltrona5frisa2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona5frisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona5frisa2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona5frisa2.setText("5");
        poltrona5frisa2.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona5frisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona5frisa2ActionPerformed(evt);
            }
        });

        polltrona1frisa3.setBackground(new java.awt.Color(39, 141, 98));
        polltrona1frisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        polltrona1frisa3.setForeground(new java.awt.Color(255, 255, 255));
        polltrona1frisa3.setText("1");
        polltrona1frisa3.setPreferredSize(new java.awt.Dimension(50, 60));
        polltrona1frisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polltrona1frisa3ActionPerformed(evt);
            }
        });

        poltrona2frisa3.setBackground(new java.awt.Color(39, 141, 98));
        poltrona2frisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona2frisa3.setForeground(new java.awt.Color(255, 255, 255));
        poltrona2frisa3.setText("2");
        poltrona2frisa3.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona2frisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona2frisa3ActionPerformed(evt);
            }
        });

        poltrona3frisa3.setBackground(new java.awt.Color(39, 141, 98));
        poltrona3frisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona3frisa3.setForeground(new java.awt.Color(255, 255, 255));
        poltrona3frisa3.setText("3");
        poltrona3frisa3.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona3frisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona3frisa3ActionPerformed(evt);
            }
        });

        poltrona4frisa3.setBackground(new java.awt.Color(39, 141, 98));
        poltrona4frisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona4frisa3.setForeground(new java.awt.Color(255, 255, 255));
        poltrona4frisa3.setText("4");
        poltrona4frisa3.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona4frisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona4frisa3ActionPerformed(evt);
            }
        });

        poltrona5frisa3.setBackground(new java.awt.Color(39, 141, 98));
        poltrona5frisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona5frisa3.setForeground(new java.awt.Color(255, 255, 255));
        poltrona5frisa3.setText("5");
        poltrona5frisa3.setPreferredSize(new java.awt.Dimension(50, 60));
        poltrona5frisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona5frisa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPoltronasLayout = new javax.swing.GroupLayout(painelPoltronas);
        painelPoltronas.setLayout(painelPoltronasLayout);
        painelPoltronasLayout.setHorizontalGroup(
            painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(poltrona1frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona3frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona5frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poltrona2frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona4frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poltrona3frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona5frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(poltrona1frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poltrona2frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona4frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poltrona3frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona5frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(polltrona1frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(poltrona2frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona4frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        painelPoltronasLayout.setVerticalGroup(
            painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronasLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poltrona2frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona2frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poltrona4frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona4frisa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(poltrona2frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(poltrona4frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poltrona1frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona1frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(polltrona1frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poltrona3frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona3frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona3frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poltrona5frisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona5frisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona5frisa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129))
        );

        etiquetaOcupado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaOcupado.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaOcupado.setText("Ocupado");

        painelOcupado.setBackground(new java.awt.Color(255, 51, 51));
        painelOcupado.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout painelOcupadoLayout = new javax.swing.GroupLayout(painelOcupado);
        painelOcupado.setLayout(painelOcupadoLayout);
        painelOcupadoLayout.setHorizontalGroup(
            painelOcupadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        painelOcupadoLayout.setVerticalGroup(
            painelOcupadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        botaoVoltar.setBackground(new java.awt.Color(21, 63, 69));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoConfirmaPoltrona.setBackground(new java.awt.Color(39, 141, 98));
        botaoConfirmaPoltrona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoConfirmaPoltrona.setForeground(new java.awt.Color(255, 255, 255));
        botaoConfirmaPoltrona.setText("Confirmar Poltrona");
        botaoConfirmaPoltrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaPoltronaActionPerformed(evt);
            }
        });

        etiquetaFrisa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaFrisa2.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaFrisa2.setText("Frisa 2");

        etiquetaFrisa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaFrisa3.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaFrisa3.setText("Frisa 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(painelPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(etiquetaFrisa1)
                        .addGap(223, 223, 223)
                        .addComponent(etiquetaFrisa2)
                        .addGap(253, 253, 253)
                        .addComponent(etiquetaFrisa3)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(painelDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaDisponivel)
                        .addGap(34, 34, 34)
                        .addComponent(painelOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaOcupado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(etiquetaTitulo)))
                .addGap(101, 103, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(botaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoConfirmaPoltrona)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(etiquetaTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelOcupado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelDisponivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaOcupado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaDisponivel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFrisa1)
                    .addComponent(etiquetaFrisa2)
                    .addComponent(etiquetaFrisa3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(painelPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoVoltar)
                            .addComponent(botaoConfirmaPoltrona))
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void poltrona1frisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona1frisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona1frisa1ActionPerformed

    private void poltrona2frisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona2frisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona2frisa1ActionPerformed

    private void poltrona3frisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona3frisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona3frisa1ActionPerformed

    private void poltrona4frisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona4frisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona4frisa1ActionPerformed

    private void poltrona5frisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona5frisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona5frisa1ActionPerformed

    private void poltrona1frisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona1frisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona1frisa2ActionPerformed

    private void poltrona2frisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona2frisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona2frisa2ActionPerformed

    private void poltrona3frisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona3frisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona3frisa2ActionPerformed

    private void poltrona4frisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona4frisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona4frisa2ActionPerformed

    private void poltrona5frisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona5frisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona5frisa2ActionPerformed

    private void polltrona1frisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polltrona1frisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polltrona1frisa3ActionPerformed

    private void poltrona2frisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona2frisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona2frisa3ActionPerformed

    private void poltrona3frisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona3frisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona3frisa3ActionPerformed

    private void poltrona4frisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona4frisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona4frisa3ActionPerformed

    private void poltrona5frisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona5frisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona5frisa3ActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoConfirmaPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaPoltronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmaPoltronaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmaPoltrona;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel etiquetaDisponivel;
    private javax.swing.JLabel etiquetaFrisa1;
    private javax.swing.JLabel etiquetaFrisa2;
    private javax.swing.JLabel etiquetaFrisa3;
    private javax.swing.JLabel etiquetaOcupado;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel painelDisponivel;
    private javax.swing.JPanel painelOcupado;
    private javax.swing.JPanel painelPoltronas;
    private javax.swing.JToggleButton polltrona1frisa3;
    private javax.swing.JToggleButton poltrona1frisa1;
    private javax.swing.JToggleButton poltrona1frisa2;
    private javax.swing.JToggleButton poltrona2frisa1;
    private javax.swing.JToggleButton poltrona2frisa2;
    private javax.swing.JToggleButton poltrona2frisa3;
    private javax.swing.JToggleButton poltrona3frisa1;
    private javax.swing.JToggleButton poltrona3frisa2;
    private javax.swing.JToggleButton poltrona3frisa3;
    private javax.swing.JToggleButton poltrona4frisa1;
    private javax.swing.JToggleButton poltrona4frisa2;
    private javax.swing.JToggleButton poltrona4frisa3;
    private javax.swing.JToggleButton poltrona5frisa1;
    private javax.swing.JToggleButton poltrona5frisa2;
    private javax.swing.JToggleButton poltrona5frisa3;
    // End of variables declaration//GEN-END:variables
}
