/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

/**
 *
 * @author WC
 */
public class PainelMenu extends javax.swing.JPanel {

    /**
     * Creates new form PainelMenu
     */
    public PainelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoComprarIngresso = new javax.swing.JButton();
        botaoMeusIngressos = new javax.swing.JButton();
        botaoEstatisticasVendas = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(950, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Pictures\\logoPi01 2.png")); // NOI18N

        botaoComprarIngresso.setBackground(new java.awt.Color(39, 141, 98));
        botaoComprarIngresso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoComprarIngresso.setForeground(new java.awt.Color(255, 255, 255));
        botaoComprarIngresso.setText("Comprar Ingressos");
        botaoComprarIngresso.setPreferredSize(new java.awt.Dimension(500, 32));

        botaoMeusIngressos.setBackground(new java.awt.Color(39, 141, 98));
        botaoMeusIngressos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoMeusIngressos.setForeground(new java.awt.Color(255, 255, 255));
        botaoMeusIngressos.setText("Meus Ingressos");
        botaoMeusIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMeusIngressosActionPerformed(evt);
            }
        });

        botaoEstatisticasVendas.setBackground(new java.awt.Color(39, 141, 98));
        botaoEstatisticasVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEstatisticasVendas.setForeground(new java.awt.Color(255, 255, 255));
        botaoEstatisticasVendas.setText("Estátisticas de Vendas");
        botaoEstatisticasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstatisticasVendasActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(21, 63, 69));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoComprarIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEstatisticasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(373, 373, 373))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoComprarIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoEstatisticasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMeusIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMeusIngressosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMeusIngressosActionPerformed

    private void botaoEstatisticasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstatisticasVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEstatisticasVendasActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComprarIngresso;
    private javax.swing.JButton botaoEstatisticasVendas;
    private javax.swing.JButton botaoMeusIngressos;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
