/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import javax.swing.*;
import java.awt.*;
import easyticket.GerenciadorIngressos;
import easyticket.Ingresso;
import easyticket.ValidadorCPF;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import easyticket.GerenciadorIngressos;
import easyticket.Ingresso;
import easyticket.ValidadorCPF;

/**
 *
 * @author WC
 */
public class PainelPlateiaA extends javax.swing.JPanel {
    private JPanel painelPrincipal;
    private GerenciadorIngressos gerenciadorIngressos;
    // Componentes do painel
    private JLabel lblTitulo;

    // Array de JToggleButtons para as poltronas
    private JToggleButton[] poltronas;
    private ButtonGroup grupoPoltronas;
    private int poltronaSelecionada = -1; // Índice da poltrona selecionada
    /**
     * Creates new form PainelPlateia
     */
    public PainelPlateiaA(JPanel painelPrincipal, GerenciadorIngressos gerenciadorIngressos) {
        this.painelPrincipal = painelPrincipal;
        this.gerenciadorIngressos = gerenciadorIngressos;
        initComponents();
        configurarPoltronas(); // Método para configurar o estado inicial das poltronas
    }

    private void initComponentsExtra() {
        // Inicializar as poltronas
        poltronas = new JToggleButton[25];
        grupoPoltronas = new ButtonGroup();

        for (int i = 0; i < 25; i++) {
            poltronas[i] = new JToggleButton(String.valueOf(i + 1));
            poltronas[i].setBackground(new Color(39, 141, 98)); // Verde escuro para disponível
            poltronas[i].setFont(new Font("Segoe UI", Font.BOLD, 14));
            poltronas[i].setForeground(Color.WHITE);
            poltronas[i].setPreferredSize(new Dimension(100, 60));
            poltronas[i].setFocusPainted(false);
            poltronas[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JToggleButton botao = (JToggleButton) e.getSource();
                    if (botao.isSelected()) {
                        botao.setBackground(Color.RED); // Vermelho para selecionado
                        poltronaSelecionada = Integer.parseInt(botao.getText()) - 1;
                    } else {
                        botao.setBackground(new Color(39, 141, 98)); // Verde escuro para disponível
                        poltronaSelecionada = -1;
                    }
                }
            });
            grupoPoltronas.add(poltronas[i]);
            painelPoltronas.add(poltronas[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaEspetaculo = new javax.swing.JLabel();
        painelDisponivel = new javax.swing.JPanel();
        etiquetaDisponivel = new javax.swing.JLabel();
        painelPoltronas = new javax.swing.JPanel();
        poltrona1 = new javax.swing.JToggleButton();
        poltrona2 = new javax.swing.JToggleButton();
        poltrona3 = new javax.swing.JToggleButton();
        poltrona4 = new javax.swing.JToggleButton();
        poltrona5 = new javax.swing.JToggleButton();
        poltrona6 = new javax.swing.JToggleButton();
        poltrona7 = new javax.swing.JToggleButton();
        poltrona8 = new javax.swing.JToggleButton();
        poltrona9 = new javax.swing.JToggleButton();
        poltrona10 = new javax.swing.JToggleButton();
        poltrona14 = new javax.swing.JToggleButton();
        poltrona13 = new javax.swing.JToggleButton();
        poltrona15 = new javax.swing.JToggleButton();
        poltrona11 = new javax.swing.JToggleButton();
        poltrona12 = new javax.swing.JToggleButton();
        poltrona16 = new javax.swing.JToggleButton();
        poltrona20 = new javax.swing.JToggleButton();
        poltrona19 = new javax.swing.JToggleButton();
        poltrona18 = new javax.swing.JToggleButton();
        poltrona17 = new javax.swing.JToggleButton();
        poltrona25 = new javax.swing.JToggleButton();
        poltrona23 = new javax.swing.JToggleButton();
        poltrona24 = new javax.swing.JToggleButton();
        poltrona21 = new javax.swing.JToggleButton();
        poltrona22 = new javax.swing.JToggleButton();
        etiquetaOcupado = new javax.swing.JLabel();
        painelOcupado = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        botaoConfirmarPoltrona = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaTitulo.setText("Escolha a Poltrona");

        etiquetaEspetaculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEspetaculo.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaEspetaculo.setText("Plateia A");

        painelDisponivel.setBackground(new java.awt.Color(39, 141, 98));
        painelDisponivel.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout painelDisponivelLayout = new javax.swing.GroupLayout(painelDisponivel);
        painelDisponivel.setLayout(painelDisponivelLayout);
        painelDisponivelLayout.setHorizontalGroup(
            painelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        painelDisponivelLayout.setVerticalGroup(
            painelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        etiquetaDisponivel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaDisponivel.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaDisponivel.setText("Disponível");

        painelPoltronas.setPreferredSize(new java.awt.Dimension(730, 415));


        poltrona1.setBackground(new java.awt.Color(39, 141, 98));
        poltrona1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona1.setForeground(new java.awt.Color(255, 255, 255));
        poltrona1.setText("1");
        poltrona1.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona1ActionPerformed(evt);
            }
        });

        poltrona2.setBackground(new java.awt.Color(39, 141, 98));
        poltrona2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona2.setForeground(new java.awt.Color(255, 255, 255));
        poltrona2.setText("2");
        poltrona2.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona2ActionPerformed(evt);
            }
        });

        poltrona3.setBackground(new java.awt.Color(39, 141, 98));
        poltrona3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona3.setForeground(new java.awt.Color(255, 255, 255));
        poltrona3.setText("3");
        poltrona3.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona3ActionPerformed(evt);
            }
        });

        poltrona4.setBackground(new java.awt.Color(39, 141, 98));
        poltrona4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona4.setForeground(new java.awt.Color(255, 255, 255));
        poltrona4.setText("4");
        poltrona4.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona4ActionPerformed(evt);
            }
        });

        poltrona5.setBackground(new java.awt.Color(39, 141, 98));
        poltrona5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona5.setForeground(new java.awt.Color(255, 255, 255));
        poltrona5.setText("5");
        poltrona5.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona5ActionPerformed(evt);
            }
        });

        poltrona6.setBackground(new java.awt.Color(39, 141, 98));
        poltrona6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona6.setForeground(new java.awt.Color(255, 255, 255));
        poltrona6.setText("6");
        poltrona6.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona6ActionPerformed(evt);
            }
        });

        poltrona7.setBackground(new java.awt.Color(39, 141, 98));
        poltrona7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona7.setForeground(new java.awt.Color(255, 255, 255));
        poltrona7.setText("7");
        poltrona7.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona7ActionPerformed(evt);
            }
        });

        poltrona8.setBackground(new java.awt.Color(39, 141, 98));
        poltrona8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona8.setForeground(new java.awt.Color(255, 255, 255));
        poltrona8.setText("8");
        poltrona8.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona8ActionPerformed(evt);
            }
        });

        poltrona9.setBackground(new java.awt.Color(39, 141, 98));
        poltrona9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona9.setForeground(new java.awt.Color(255, 255, 255));
        poltrona9.setText("9");
        poltrona9.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona9ActionPerformed(evt);
            }
        });

        poltrona10.setBackground(new java.awt.Color(39, 141, 98));
        poltrona10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona10.setForeground(new java.awt.Color(255, 255, 255));
        poltrona10.setText("10");
        poltrona10.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona10ActionPerformed(evt);
            }
        });

        poltrona14.setBackground(new java.awt.Color(39, 141, 98));
        poltrona14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona14.setForeground(new java.awt.Color(255, 255, 255));
        poltrona14.setText("14");
        poltrona14.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona14ActionPerformed(evt);
            }
        });

        poltrona13.setBackground(new java.awt.Color(39, 141, 98));
        poltrona13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona13.setForeground(new java.awt.Color(255, 255, 255));
        poltrona13.setText("13");
        poltrona13.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona13ActionPerformed(evt);
            }
        });

        poltrona15.setBackground(new java.awt.Color(39, 141, 98));
        poltrona15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona15.setForeground(new java.awt.Color(255, 255, 255));
        poltrona15.setText("15");
        poltrona15.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona15ActionPerformed(evt);
            }
        });

        poltrona11.setBackground(new java.awt.Color(39, 141, 98));
        poltrona11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona11.setForeground(new java.awt.Color(255, 255, 255));
        poltrona11.setText("11");
        poltrona11.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona11ActionPerformed(evt);
            }
        });

        poltrona12.setBackground(new java.awt.Color(39, 141, 98));
        poltrona12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona12.setForeground(new java.awt.Color(255, 255, 255));
        poltrona12.setText("12");
        poltrona12.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona12ActionPerformed(evt);
            }
        });

        poltrona16.setBackground(new java.awt.Color(39, 141, 98));
        poltrona16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona16.setForeground(new java.awt.Color(255, 255, 255));
        poltrona16.setText("16");
        poltrona16.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona16ActionPerformed(evt);
            }
        });

        poltrona20.setBackground(new java.awt.Color(39, 141, 98));
        poltrona20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona20.setForeground(new java.awt.Color(255, 255, 255));
        poltrona20.setText("20");
        poltrona20.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona20ActionPerformed(evt);
            }
        });

        poltrona19.setBackground(new java.awt.Color(39, 141, 98));
        poltrona19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona19.setForeground(new java.awt.Color(255, 255, 255));
        poltrona19.setText("19");
        poltrona19.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona19ActionPerformed(evt);
            }
        });

        poltrona18.setBackground(new java.awt.Color(39, 141, 98));
        poltrona18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona18.setForeground(new java.awt.Color(255, 255, 255));
        poltrona18.setText("18");
        poltrona18.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona18ActionPerformed(evt);
            }
        });

        poltrona17.setBackground(new java.awt.Color(39, 141, 98));
        poltrona17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona17.setForeground(new java.awt.Color(255, 255, 255));
        poltrona17.setText("17");
        poltrona17.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona17ActionPerformed(evt);
            }
        });

        poltrona25.setBackground(new java.awt.Color(39, 141, 98));
        poltrona25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona25.setForeground(new java.awt.Color(255, 255, 255));
        poltrona25.setText("25");
        poltrona25.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona25ActionPerformed(evt);
            }
        });

        poltrona23.setBackground(new java.awt.Color(39, 141, 98));
        poltrona23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona23.setForeground(new java.awt.Color(255, 255, 255));
        poltrona23.setText("23");
        poltrona23.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona23ActionPerformed(evt);
            }
        });

        poltrona24.setBackground(new java.awt.Color(39, 141, 98));
        poltrona24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona24.setForeground(new java.awt.Color(255, 255, 255));
        poltrona24.setText("24");
        poltrona24.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona24ActionPerformed(evt);
            }
        });

        poltrona21.setBackground(new java.awt.Color(39, 141, 98));
        poltrona21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona21.setForeground(new java.awt.Color(255, 255, 255));
        poltrona21.setText("21");
        poltrona21.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona21ActionPerformed(evt);
            }
        });

        poltrona22.setBackground(new java.awt.Color(39, 141, 98));
        poltrona22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        poltrona22.setForeground(new java.awt.Color(255, 255, 255));
        poltrona22.setText("22");
        poltrona22.setPreferredSize(new java.awt.Dimension(119, 63));
        poltrona22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPoltronasLayout = new javax.swing.GroupLayout(painelPoltronas);
        painelPoltronas.setLayout(painelPoltronasLayout);
        painelPoltronasLayout.setHorizontalGroup(
            painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addComponent(poltrona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addComponent(poltrona6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addComponent(poltrona11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addComponent(poltrona16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPoltronasLayout.createSequentialGroup()
                        .addComponent(poltrona21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poltrona25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        painelPoltronasLayout.setVerticalGroup(
            painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poltrona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poltrona6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poltrona11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poltrona16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelPoltronasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poltrona21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltrona25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        etiquetaOcupado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaOcupado.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaOcupado.setText("Ocupado");

        painelOcupado.setBackground(new java.awt.Color(255, 51, 51));
        painelOcupado.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout painelOcupadoLayout = new javax.swing.GroupLayout(painelOcupado);
        painelOcupado.setLayout(painelOcupadoLayout);
        painelOcupadoLayout.setHorizontalGroup(
            painelOcupadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        painelOcupadoLayout.setVerticalGroup(
            painelOcupadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        botaoVoltar.setBackground(new java.awt.Color(21, 63, 69));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                navigateToPanel("Comprar");
            }
        });

        botaoConfirmarPoltrona.setBackground(new java.awt.Color(39, 141, 98));
        botaoConfirmarPoltrona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoConfirmarPoltrona.setForeground(new java.awt.Color(255, 255, 255));
        botaoConfirmarPoltrona.setText("Escolher Poltrona");
        botaoConfirmarPoltrona.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                confirmarPoltrona();
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(etiquetaTitulo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(botaoVoltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                            .addComponent(botaoConfirmarPoltrona))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(etiquetaEspetaculo)
                                    .addGap(51, 51, 51)
                                    .addComponent(painelDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(etiquetaDisponivel)
                                    .addGap(34, 34, 34)
                                    .addComponent(painelOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(etiquetaOcupado))
                                .addComponent(painelPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(etiquetaTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaEspetaculo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelOcupado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelDisponivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaOcupado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaDisponivel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addComponent(painelPoltronas, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoConfirmarPoltrona))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void poltrona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona1ActionPerformed

    private void poltrona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona2ActionPerformed

    private void poltrona3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona3ActionPerformed

    private void poltrona4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona4ActionPerformed

    private void poltrona5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona5ActionPerformed

    private void poltrona6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona6ActionPerformed

    private void poltrona7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona7ActionPerformed

    private void poltrona8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona8ActionPerformed

    private void poltrona9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona9ActionPerformed

    private void poltrona10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona10ActionPerformed

    private void poltrona14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona14ActionPerformed

    private void poltrona13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona13ActionPerformed

    private void poltrona15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona15ActionPerformed

    private void poltrona11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona11ActionPerformed

    private void poltrona12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona12ActionPerformed

    private void poltrona16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona16ActionPerformed

    private void poltrona20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona20ActionPerformed

    private void poltrona19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona19ActionPerformed

    private void poltrona18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona18ActionPerformed

    private void poltrona17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona17ActionPerformed

    private void poltrona25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona25ActionPerformed

    private void poltrona23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona23ActionPerformed

    private void poltrona24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona24ActionPerformed

    private void poltrona21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona21ActionPerformed

    private void poltrona22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poltrona22ActionPerformed


    private void botaoConfirmarPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarPoltronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmarPoltronaActionPerformed

    /**
     * Método para configurar o estado inicial das poltronas com base nas reservas existentes.
     */
    private void configurarPoltronas() {
        Ingresso[] ingressos = gerenciadorIngressos.getIngressosReservados();
        for (Ingresso ingresso : ingressos) {
            if (ingresso.getArea().equals("Plateia A")) {
                int poltrona = ingresso.getPoltrona();
                if (poltrona >= 0 && poltrona < poltronas.length) {
                    poltronas[poltrona].setBackground(Color.RED);
                    poltronas[poltrona].setEnabled(false); // Desabilita a poltrona se já estiver reservada
                }
            }
        }
    }

    private void confirmarPoltrona() {
        if (poltronaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma poltrona.", "Nenhuma Poltrona Selecionada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cpf = JOptionPane.showInputDialog(this, "Digite o CPF para confirmação:");

        if (cpf == null || cpf.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CPF é obrigatório para confirmar a poltrona.", "CPF Obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        cpf = cpf.trim();

        // Validar CPF
        if (!ValidadorCPF.validaCPF(cpf)) {
            JOptionPane.showMessageDialog(this, "CPF inválido. Por favor, insira um CPF válido.", "CPF Inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Criar o ingresso
        String espetaculo = gerenciadorIngressos.getEspetaculoSelecionado();
        String sessao = gerenciadorIngressos.getSessaoSelecionada();
        String area = gerenciadorIngressos.getAreaSelecionada();
        double preco = 40.00; // Preço para Plateia A - R$40

        Ingresso ingresso = new Ingresso(cpf, espetaculo, sessao, area, poltronaSelecionada, preco);

        // Finalizar a compra
        gerenciadorIngressos.finalizarCompra(ingresso);

        // Atualizar a UI para refletir a poltrona reservada
        poltronas[poltronaSelecionada].setBackground(Color.RED);
        poltronas[poltronaSelecionada].setEnabled(false);
        grupoPoltronas.clearSelection();
        poltronaSelecionada = -1;

        // Redirecionar para IngressoComprado
        navigateToPanel("IngressoComprado");
    }

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        navigateToPanel("Comprar");  // Nome correto do painel para retornar
    }

    private void navigateToPanel(String panelName) {
        CardLayout layout = (CardLayout) painelPrincipal.getLayout();
        layout.show(painelPrincipal, panelName);
        painelPrincipal.revalidate();
        painelPrincipal.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmarPoltrona;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel etiquetaDisponivel;
    private javax.swing.JLabel etiquetaEspetaculo;
    private javax.swing.JLabel etiquetaOcupado;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel painelDisponivel;
    private javax.swing.JPanel painelOcupado;
    private javax.swing.JPanel painelPoltronas;
    private javax.swing.JToggleButton poltrona1;
    private javax.swing.JToggleButton poltrona10;
    private javax.swing.JToggleButton poltrona11;
    private javax.swing.JToggleButton poltrona12;
    private javax.swing.JToggleButton poltrona13;
    private javax.swing.JToggleButton poltrona14;
    private javax.swing.JToggleButton poltrona15;
    private javax.swing.JToggleButton poltrona16;
    private javax.swing.JToggleButton poltrona17;
    private javax.swing.JToggleButton poltrona18;
    private javax.swing.JToggleButton poltrona19;
    private javax.swing.JToggleButton poltrona2;
    private javax.swing.JToggleButton poltrona20;
    private javax.swing.JToggleButton poltrona21;
    private javax.swing.JToggleButton poltrona22;
    private javax.swing.JToggleButton poltrona23;
    private javax.swing.JToggleButton poltrona24;
    private javax.swing.JToggleButton poltrona25;
    private javax.swing.JToggleButton poltrona3;
    private javax.swing.JToggleButton poltrona4;
    private javax.swing.JToggleButton poltrona5;
    private javax.swing.JToggleButton poltrona6;
    private javax.swing.JToggleButton poltrona7;
    private javax.swing.JToggleButton poltrona8;
    private javax.swing.JToggleButton poltrona9;
    // End of variables declaration//GEN-END:variables
}
