/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

/**
 *
 * @author WC
 */
public class PainelIngressoComprado extends javax.swing.JPanel {

    /**
     * Creates new form PainelIngressoComprado
     */
    public PainelIngressoComprado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        painelEspetaculo = new javax.swing.JPanel();
        etiquetaEspetaculo = new javax.swing.JLabel();
        painelCampoEspetaculo = new javax.swing.JPanel();
        campoEspetaculo = new javax.swing.JTextField();
        painelSessao = new javax.swing.JPanel();
        etiquetaSessao = new javax.swing.JLabel();
        painelCampoSessao = new javax.swing.JPanel();
        campoSessao = new javax.swing.JTextField();
        painelCampoArea = new javax.swing.JPanel();
        campoArea = new javax.swing.JTextField();
        painelArea = new javax.swing.JPanel();
        etiquetaArea = new javax.swing.JLabel();
        painelPoltrona = new javax.swing.JPanel();
        etiquetaPoltrona = new javax.swing.JLabel();
        painelCampoPoltrona = new javax.swing.JPanel();
        campoPoltrona = new javax.swing.JTextField();
        painelCampoPreco = new javax.swing.JPanel();
        campoPreco = new javax.swing.JTextField();
        painelPreco = new javax.swing.JPanel();
        etiquetaPreco = new javax.swing.JLabel();
        botaoVoltarMenu = new javax.swing.JButton();
        botaoComprarNovamente = new javax.swing.JButton();
        botaoMeusIngressos = new javax.swing.JButton();

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(21, 63, 69));
        etiquetaTitulo.setText("Ingresso Comprado");

        painelEspetaculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 63, 69), 1, true));
        painelEspetaculo.setPreferredSize(new java.awt.Dimension(120, 41));

        etiquetaEspetaculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEspetaculo.setText("Espetáculo");

        javax.swing.GroupLayout painelEspetaculoLayout = new javax.swing.GroupLayout(painelEspetaculo);
        painelEspetaculo.setLayout(painelEspetaculoLayout);
        painelEspetaculoLayout.setHorizontalGroup(
            painelEspetaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEspetaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaEspetaculo, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelEspetaculoLayout.setVerticalGroup(
            painelEspetaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEspetaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaEspetaculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCampoEspetaculo.setBackground(new java.awt.Color(255, 255, 255));
        painelCampoEspetaculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 69)));
        painelCampoEspetaculo.setPreferredSize(new java.awt.Dimension(120, 41));

        javax.swing.GroupLayout painelCampoEspetaculoLayout = new javax.swing.GroupLayout(painelCampoEspetaculo);
        painelCampoEspetaculo.setLayout(painelCampoEspetaculoLayout);
        painelCampoEspetaculoLayout.setHorizontalGroup(
            painelCampoEspetaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCampoEspetaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoEspetaculo, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCampoEspetaculoLayout.setVerticalGroup(
            painelCampoEspetaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCampoEspetaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoEspetaculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelSessao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 63, 69), 1, true));
        painelSessao.setPreferredSize(new java.awt.Dimension(120, 41));

        etiquetaSessao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaSessao.setText("Sessão");

        javax.swing.GroupLayout painelSessaoLayout = new javax.swing.GroupLayout(painelSessao);
        painelSessao.setLayout(painelSessaoLayout);
        painelSessaoLayout.setHorizontalGroup(
            painelSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSessaoLayout.setVerticalGroup(
            painelSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCampoSessao.setBackground(new java.awt.Color(255, 255, 255));
        painelCampoSessao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 69)));
        painelCampoSessao.setPreferredSize(new java.awt.Dimension(120, 41));

        javax.swing.GroupLayout painelCampoSessaoLayout = new javax.swing.GroupLayout(painelCampoSessao);
        painelCampoSessao.setLayout(painelCampoSessaoLayout);
        painelCampoSessaoLayout.setHorizontalGroup(
            painelCampoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCampoSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCampoSessaoLayout.setVerticalGroup(
            painelCampoSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCampoSessaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCampoArea.setBackground(new java.awt.Color(255, 255, 255));
        painelCampoArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 69)));
        painelCampoArea.setPreferredSize(new java.awt.Dimension(120, 41));

        javax.swing.GroupLayout painelCampoAreaLayout = new javax.swing.GroupLayout(painelCampoArea);
        painelCampoArea.setLayout(painelCampoAreaLayout);
        painelCampoAreaLayout.setHorizontalGroup(
            painelCampoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCampoAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoArea, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCampoAreaLayout.setVerticalGroup(
            painelCampoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCampoAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoArea, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 63, 69), 1, true));
        painelArea.setPreferredSize(new java.awt.Dimension(120, 41));

        etiquetaArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaArea.setText("Área");

        javax.swing.GroupLayout painelAreaLayout = new javax.swing.GroupLayout(painelArea);
        painelArea.setLayout(painelAreaLayout);
        painelAreaLayout.setHorizontalGroup(
            painelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaArea, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelAreaLayout.setVerticalGroup(
            painelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaArea, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPoltrona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 63, 69), 1, true));
        painelPoltrona.setPreferredSize(new java.awt.Dimension(120, 41));

        etiquetaPoltrona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaPoltrona.setText("Poltrona");

        javax.swing.GroupLayout painelPoltronaLayout = new javax.swing.GroupLayout(painelPoltrona);
        painelPoltrona.setLayout(painelPoltronaLayout);
        painelPoltronaLayout.setHorizontalGroup(
            painelPoltronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPoltrona, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelPoltronaLayout.setVerticalGroup(
            painelPoltronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoltronaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPoltrona, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCampoPoltrona.setBackground(new java.awt.Color(255, 255, 255));
        painelCampoPoltrona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 69)));
        painelCampoPoltrona.setPreferredSize(new java.awt.Dimension(120, 41));

        javax.swing.GroupLayout painelCampoPoltronaLayout = new javax.swing.GroupLayout(painelCampoPoltrona);
        painelCampoPoltrona.setLayout(painelCampoPoltronaLayout);
        painelCampoPoltronaLayout.setHorizontalGroup(
            painelCampoPoltronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCampoPoltronaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPoltrona, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCampoPoltronaLayout.setVerticalGroup(
            painelCampoPoltronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCampoPoltronaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPoltrona, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCampoPreco.setBackground(new java.awt.Color(255, 255, 255));
        painelCampoPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 69)));
        painelCampoPreco.setPreferredSize(new java.awt.Dimension(120, 41));

        javax.swing.GroupLayout painelCampoPrecoLayout = new javax.swing.GroupLayout(painelCampoPreco);
        painelCampoPreco.setLayout(painelCampoPrecoLayout);
        painelCampoPrecoLayout.setHorizontalGroup(
            painelCampoPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCampoPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCampoPrecoLayout.setVerticalGroup(
            painelCampoPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCampoPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPreco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 63, 69), 1, true));
        painelPreco.setPreferredSize(new java.awt.Dimension(120, 41));

        etiquetaPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaPreco.setText("Preço");

        javax.swing.GroupLayout painelPrecoLayout = new javax.swing.GroupLayout(painelPreco);
        painelPreco.setLayout(painelPrecoLayout);
        painelPrecoLayout.setHorizontalGroup(
            painelPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrecoLayout.setVerticalGroup(
            painelPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoVoltarMenu.setBackground(new java.awt.Color(21, 63, 69));
        botaoVoltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltarMenu.setText("Voltar ao Menu");
        botaoVoltarMenu.setPreferredSize(new java.awt.Dimension(150, 40));

        botaoComprarNovamente.setBackground(new java.awt.Color(39, 141, 98));
        botaoComprarNovamente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoComprarNovamente.setForeground(new java.awt.Color(255, 255, 255));
        botaoComprarNovamente.setText("Comprar Novamente");
        botaoComprarNovamente.setPreferredSize(new java.awt.Dimension(150, 40));

        botaoMeusIngressos.setBackground(new java.awt.Color(21, 63, 69));
        botaoMeusIngressos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoMeusIngressos.setForeground(new java.awt.Color(255, 255, 255));
        botaoMeusIngressos.setText("Meus Ingressos");
        botaoMeusIngressos.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoMeusIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMeusIngressosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(painelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(painelCampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(painelPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(painelCampoPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(etiquetaTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(painelEspetaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCampoEspetaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCampoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCampoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoComprarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(etiquetaTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelEspetaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCampoEspetaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCampoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCampoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCampoPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoComprarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMeusIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMeusIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMeusIngressosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMeusIngressosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComprarNovamente;
    private javax.swing.JButton botaoMeusIngressos;
    private javax.swing.JButton botaoVoltarMenu;
    private javax.swing.JTextField campoArea;
    private javax.swing.JTextField campoEspetaculo;
    private javax.swing.JTextField campoPoltrona;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JTextField campoSessao;
    private javax.swing.JLabel etiquetaArea;
    private javax.swing.JLabel etiquetaEspetaculo;
    private javax.swing.JLabel etiquetaPoltrona;
    private javax.swing.JLabel etiquetaPreco;
    private javax.swing.JLabel etiquetaSessao;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel painelArea;
    private javax.swing.JPanel painelCampoArea;
    private javax.swing.JPanel painelCampoEspetaculo;
    private javax.swing.JPanel painelCampoPoltrona;
    private javax.swing.JPanel painelCampoPreco;
    private javax.swing.JPanel painelCampoSessao;
    private javax.swing.JPanel painelEspetaculo;
    private javax.swing.JPanel painelPoltrona;
    private javax.swing.JPanel painelPreco;
    private javax.swing.JPanel painelSessao;
    // End of variables declaration//GEN-END:variables
}
